### ISSUE TITLE
add extra feature for time window

### ISSUE THREAD

**Issue by beyhangl** [Khixinhxan/vrp_ortools_python#1]
Hi, thank you for this great experience sharing. It's a really promising repository for future projects.

I want to tell you about my specific feature.

As you know we have some time windows to visit clients. I need extra control for back to depot before it closes.

So depots is open between 08:00 and 18:00 so vehicles have to back to their depots before close.

Do you know how can we add this feature into the time window?

Thanks

**Comment by Khixinhxan** [comment]
Tks @beyhangl for the feedback!
I think you can use VRPTW_model (Vehicle Route Problem Time Window)
Default, the depot have index by 0, you can set this time window for depot is [8, 18] in data input.
https://github.com/Khixinhxan/vrp_ortools_python/blob/66b9de866c0fd97077eb12e43d9ce268b9d2ae8d/VRPTW_model%20(Vehicle%20Route%20Problem%20Time%20Window)/vrp_tw_example.py#L34

And this time window of depot be applied on model by
https://github.com/Khixinhxan/vrp_ortools_python/blob/66b9de866c0fd97077eb12e43d9ce268b9d2ae8d/VRPTW_model%20(Vehicle%20Route%20Problem%20Time%20Window)/vrp_tw_example.py#L116

**Comment by beyhangl** [comment]
Thank you. I've solved it with that code block
```
    for vehicle_id in range(data['num_vehicles']):
        index = routing.End(vehicle_id)
        time_dimension.CumulVar(index).SetRange(data['time_windows'][0][0],
                                                data['time_windows'][0][1])
```
